config/routes.rb
Rails.application.routes.draw do
  get 'changes/index'
  resources :transactions
  get 'transactions/index'
  get 'transactions/new'
  post 'transactions/preview'

  resources :stocks
  get 'stocks/index'
  get 'stocks/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/change.rb
class Change < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  def index
    @changes = Change.all
  end

  def show
    @change = Change.find(params[:id])
  end

  def new
    @stocks = Stock.all
    @change = Change.new
  end

  def create
    @change = Change.new(change_params)

    if @change.save
      redirect_to changes_path
    else
      render 'new'
    end

  end

  def edit
    @change = Changes.find(params[:id])
  end

  def update
    @change = Change.find(params[:id])

    if @change.update(change_params)
      redirect_to changes_path
    else
      render 'edit'
    end

  end

  def destroy
    @change = Change.find(params[:id])
    @change.destroy
    redirect_to changes_path
  end

  private
    def change_params
      params.require(:change).permit(:id, :amount, :type, :stock_id)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to stocks_path
    else
      render 'new'
    end

  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])

    if @stock.update(stock_params)
      redirect_to stocks_path
    else
      render 'edit'
    end

  end

  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy
    redirect_to stocks_path
  end

  private
    def stock_params
      params.require(:stock).permit(:idStock, :namaBarang, :hargaBarang, :jumlagStock)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction  = Transaction.new
    @stocks       = Stock.all
  end
  
  def create

    step          = params[:step]
    
    if step == 'preview'
      total     = 0
      @keranjang = params[:keranjang]
      @keranjang.each do |index, val| 
        item  = Stock.find_by(id: index)
        total += (val.to_i * item.hargaBarang) 
      end

      @bayar = total
      @transaction  = Transaction.new

    elsif step == 'save'

      @transaction = Transaction.new(transaction_params)

      if @transaction.save

        keranjang = params[:keranjang]
        keranjang.each do |index, val| 
          Detail.create(transaction_id: @transaction.id, stock_id: index, amount:val )
        end

        redirect_to transactions_path
      else
        render 'new'
      end
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(transaction_params)
      redirect_to transactions_path
    else
      render 'edit'
    end

  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to transactions_path
  end

  private
    def transaction_params
      params.require(:transaction).permit(:idTransaction, :dateTransaction, :totalTransaction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/changes/index.html.erb
<h1>Changes#index</h1>
<p>Find me in app/views/changes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kasirapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/_form.erb
<div class="container">
  <div class="row">
    <%= form_for(@stock) do |stock| %>

        <div class="form-group">
          <%= stock.label :ID_Barang %>
          <%= stock.text_field :idStock, class:'form-control', type: 'text', placeholder: 'ID Barang' %>
        </div>

        <div class="form-group">
          <%= stock.label :Nama_Barang %>
          <%= stock.text_field :namaBarang, class:'form-control', type: 'text', placeholder: 'Nama Barang' %>
        </div>

        <div class="form-group">
          <%= stock.label :Harga_Barang %>
          <%= stock.text_field :hargaBarang, class:'form-control', type: 'text', placeholder: 'Harga Barang' %>
        </div>

        <div class="form-group">
          <%= stock.label :Jumlah_Stock %>
          <%= stock.text_field :jumlagStock, class:'form-control', type: 'text', placeholder: 'Jumlah' %>
        </div>

        <%= stock.submit :Save, class:'btn btn-success' %>
        <%= link_to 'Back', 'javascript:history.back()' %>

    <% end %>
  </div>
</div>

app/views/stocks/_navigation.erb
<%= link_to 'Lakukan Transaksi', transactions_new_path, class: 'btn btn-default' %> | 
<%= link_to 'Tambah Barang', stocks_new_path, class: 'btn btn-default' %> | 
<%= link_to 'Data Barang', stocks_path, class: 'btn btn-default' %> | 
<%= link_to 'Histori Transaksi', transactions_path, class: 'btn btn-default' %>

app/views/stocks/edit.html.erb
<%= render 'form' %>

app/views/stocks/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'navigation' %>
    <h2>Data Barang Saat Ini</h2>
    <%= link_to 'Tambah Stock', stocks_new_path, class: 'btn btn-default' %>
    <table border="1" class="table table-bordered table-hover table-responsive">
      <thead>
      <tr>
        <th class="text-center">Id Barang</th>
        <th class="text-center">Nama Barang</th>
        <th class="text-center">Harga Barang</th>
        <th class="text-center">Persediaan</th>
        <th class="text-center">Aksi</th>
      </tr>
      </thead>
      <tbody>
      <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.idStock %></td>
            <td><%= stock.namaBarang %></td>
            <td><%= stock.hargaBarang %></td>
            <td><%= stock.jumlagStock %></td>
            <td class="text-center">
              <%= link_to 'Detail', stock_path(stock), class: 'btn btn-default' %>
              <%= link_to 'Edit', edit_stock_path(stock), class: 'btn btn-success' %>
              <%= link_to 'Delete',stock_path(stock), method: :delete, data: {confirm: 'Data Dihapus ? '}, class: 'btn btn-danger' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/new.html.erb
<h2>Tambah data barang:</h2>
<%= render 'form' %>

app/views/stocks/show.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@stock) do |stock| %>

        <div class="form-group">
          <%= stock.label :ID_Barang %>
          <%= stock.text_field :idStock, class:'form-control', type: 'text', placeholder: 'ID Barang', disabled: true  %>
        </div>

        <div class="form-group">
          <%= stock.label :Nama_Barang %>
          <%= stock.text_field :namaBarang, class:'form-control', type: 'text', placeholder: 'Nama Barang', disabled: true  %>
        </div>

        <div class="form-group">
          <%= stock.label :Harga_Barang %>
          <%= stock.text_field :hargaBarang, class:'form-control', type: 'text', placeholder: 'Harga Barang', disabled: true  %>
        </div>

        <div class="form-group">
          <%= stock.label :Jumlah_Stock %>
          <%= stock.text_field :jumlagStock, class:'form-control', type: 'text', placeholder: 'Jumlah', disabled: true  %>
        </div>

    <% end %>
  </div>
</div>

app/views/transactions/create.html.erb
<h3>Total Belanja: <b>Rp.<%= @bayar %></b></h3>

<%= form_for @transaction do |transaction| %>

    <%= transaction.hidden_field :totalTransaction, value:@bayar %>
    <%= hidden_field_tag(:step, "save") %>

    <% @keranjang.each do | index, val | %>  
        <%= hidden_field_tag('keranjang['+index+']', val) %>
    <% end %>

    <%= transaction.submit :Lanjutkan, class:'btn btn-success' %>
    <%= link_to 'Kembali', 'javascript:history.back()' %>

<% end %>

app/views/transactions/index.html.erb
<div class="container">
  <div class="row">
  <%= render 'stocks/navigation' %>
    <h2>Terserah</h2>
    <table border="1" class="table table-bordered table-hover table-responsive">
      <thead>
      <tr>
        <th class="text-center">Id Transaksi</th>
        <th class="text-center">Tanggal Transaksi</th>
        <th class="text-center">Total Bayar</th>
      </tr>
      </thead>
      <tbody>
      <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.id %></td>
            <td><%= transaction.created_at %></td>
            <td><%= transaction.totalTransaction %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for @transaction do |transaction| %>

        <h2>Pilih barang yang dibeli:</h2>
        <%= hidden_field_tag(:step, "preview") %>
        <% @stocks.each do |stock| %>
            <div style="width:500px;border:1px solid #ddd;padding:10px;margin-bottom:-1px">
                <%= number_field_tag 'keranjang['+stock.id.to_s+']', 0, min:0, max:stock.jumlagStock  %>
                <%= stock.namaBarang %>
                <b style="float:right">Rp.<%= stock.hargaBarang %></b>
            </div>
        <% end %>
        
        <br>

        <%= transaction.submit :Save, class:'btn btn-success' %>
        <%= link_to 'Back', 'javascript:history.back()' %>

    <% end %>
  </div>
</div>